[[kubectl]]
arch = "aarch64"
git-tree-sha1 = "9c08c39a431163a4d9f08736e7f85d23057fe188"
os = "macos"

    [[kubectl.download]]
    sha256 = "2509086b1a68d46facb00ff0268f5ee23e50b74e93d98c776b60eef8dff239b7"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.30.1+0/kubectl.v1.30.1.aarch64-apple-darwin.tar.gz"
[[kubectl]]
arch = "aarch64"
git-tree-sha1 = "fb8cc369abd58eaef1d9041d0826f5666c169c19"
libc = "glibc"
os = "linux"

    [[kubectl.download]]
    sha256 = "186a979eb34f3299c9bfe3d79948ef3dbecb57e6a6baf3d34829dfbf87a12fb7"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.30.1+0/kubectl.v1.30.1.aarch64-linux-gnu.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "a3cebb28193b8ff17a5182e6230bb42950aa5d34"
os = "macos"

    [[kubectl.download]]
    sha256 = "a7f10aeb563a4f90a951fb1fa25036aab562fd37099e2da9e5f3712edd42269f"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.30.1+0/kubectl.v1.30.1.x86_64-apple-darwin.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "5d4f97afc577e64281e392251bc6afe7216a24ee"
libc = "glibc"
os = "linux"

    [[kubectl.download]]
    sha256 = "b429ccc0cf408558997c007a9a261937c999b6436f1b23628ee843659984b938"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.30.1+0/kubectl.v1.30.1.x86_64-linux-gnu.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "6db2a4eaad94c2b45013e10d38d28102f3ecbf4a"
os = "windows"

    [[kubectl.download]]
    sha256 = "860ba07eaea7b05c4daaf5ac95675aba0db1d373120b74faa47dafd1fab3c51c"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.30.1+0/kubectl.v1.30.1.x86_64-w64-mingw32.tar.gz"
