[[kubectl]]
arch = "aarch64"
git-tree-sha1 = "643d8b85d84186b0e6340b4f9cb201967dbd7693"
libc = "glibc"
os = "linux"

    [[kubectl.download]]
    sha256 = "e93d776770c548ec2a6b116f582f2b9725900d89cec2511f4fdb55d256b0726b"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.20.0+1/kubectl.v1.20.0.aarch64-linux-gnu.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "f7f4738da9ad3f9ae5ce44f1534e4d2fef378dbd"
os = "macos"

    [[kubectl.download]]
    sha256 = "d5326131a375dd593308c9662413dd57d59ef8c3b867bb231c2a5e1d64d06531"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.20.0+1/kubectl.v1.20.0.x86_64-apple-darwin.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "e549ab3a763d3b31e726aa6336c6dbb75ee90a05"
libc = "glibc"
os = "linux"

    [[kubectl.download]]
    sha256 = "54d2b2672f1821f72daf6a2ce73e08d3c8d6b15c89799478c39e8b731b49f0c6"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.20.0+1/kubectl.v1.20.0.x86_64-linux-gnu.tar.gz"
[[kubectl]]
arch = "x86_64"
git-tree-sha1 = "0fbfc6769988179faafab36117731511b1865ed4"
os = "windows"

    [[kubectl.download]]
    sha256 = "89c2d5c44db8c1904d3111807a213d8ec3ce67247c98c0b523034d42bd9b9e15"
    url = "https://github.com/JuliaBinaryWrappers/kubectl_jll.jl/releases/download/kubectl-v1.20.0+1/kubectl.v1.20.0.x86_64-w64-mingw32.tar.gz"
